/* Prologue
  // Name: reportWebVitals.js
  // Description: Display performance metrics using a provided logging function
  // Programmer: None (This was generated by the create-react-app tool by Facebook and has not been modified)
  // Creation date: 10/23/25
  // Revisions: 0.0
  // Pre/post conditions
  //   - Pre: A logging function is provided for use. 
  //   - Post: Logged data reported.
  // Errors: None. 
*/

const reportWebVitals = onPerfEntry => {
  if (onPerfEntry && onPerfEntry instanceof Function) {
    import('web-vitals').then(({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {
      getCLS(onPerfEntry);
      getFID(onPerfEntry);
      getFCP(onPerfEntry);
      getLCP(onPerfEntry);
      getTTFB(onPerfEntry);
    });
  }
};

export default reportWebVitals;
