/* Prologue
  // Name: setupTests.js
  // Description: Prepare and run tests
  // Programmer: None (This was generated by the create-react-app tool by Facebook and has not been modified)
  // Creation date: 10/23/25
  // Revisions: 0.0
  // Pre/post conditions
  //   - Pre: None. 
  //   - Post: None.
  // Errors: None. 
*/

// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom';
